# Linux build environment for CI

FROM ubuntu:bionic

ARG CMAKE_VERSION=3.19.2

# GCC 8 is needed for newer std c++17 libs

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends  \
      ca-certificates                           \
      git                                       \
      python3                                   \
      wget                                      \
      gcc-8 g++-8                               \
      clang-format-9                            \
      clang-9                                   \
      llvm-9-dev                                \
      libc++-9-dev                              \
      libc++abi-9-dev                           \
      libgtk-3-dev                              \
      liblz4-dev                                \
      libpthread-stubs0-dev                     \
      libsdl2-dev                               \
      libvulkan-dev                             \
      libx11-dev                                \
    ; \
    rm -rf /var/lib/apt/lists/*

RUN wget -O /root/cmake.sh https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh; \
    chmod +x /root/cmake.sh; \
    /root/cmake.sh --skip-license; \
    rm /root/cmake.sh; \
    cmake --version

RUN ln -s clang-format-9 /usr/bin/clang-format
RUN ln -s clang-9 /usr/bin/clang
RUN ln -s clang++-9 /usr/bin/clang++
RUN ln -s llvm-ar-9 /usr/bin/llvm-ar

ENV CC clang
ENV CXX clang++
ENV AR llvm-ar
